### ISSUE TITLE
Private Key might leak

### ISSUE THREAD

**Issue by sklemer1** [IdentityPython/pyXMLSecurity#47]
Because of

https://github.com/IdentityPython/pyXMLSecurity/blob/2a34bcac61cbd85a772354752a95f3c1bc1e5e5f/src/xmlsec/__init__.py#L479

we might leak the private key if e.g. `cert_spec=None` . This is very dangerous. I'm not completely sure how this interacts with pkcs11 -- will post a follow up soon.

**Comment by sklemer1** [comment]
@leifj @fredrikt @c00kiemon5ter  this is pretty grave -- even if you don't like my approach to fix it, we should do something.

This is for example triggered by a pyff-config like:

```
[...]
             - sign:
                 key: /etc/ssl/private/privkey.priv
             - publish: foobar.xml
```
(i.e. withouth a `cert`-statement in the `sign`-clause)
